import { relations } from 'drizzle-orm';
import { integer, bigint, pgTable, serial, bigserial, text, timestamp, varchar, date, boolean, json, jsonb, doublePrecision, pgEnum, index, uniqueIndex } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(),
  email: text('email').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

export const SignalDirectionEnum = pgEnum('signaldirection', ['BUY', 'SELL', 'HOLD']);

export const OrderStatusEnum = pgEnum('orderstatus', ['PENDING', 'FILLED', 'CANCELLED', 'REJECTED']);

export const AlertLevelEnum = pgEnum('alertlevel', ['INFO', 'WARNING', 'CRITICAL', 'EMERGENCY']);

export const PositionStatusEnum = pgEnum('positionstatus', ['OPEN', 'CLOSED']);

export const contracts = pgTable('contracts', {
  id: serial('id').primaryKey(),
  symbol: text('symbol').notNull(),
  name: text('name').notNull(),
  exchange: text('exchange').notNull(),
  category: text('category').notNull(),
  multiplier: integer('multiplier').notNull(),
  min_tick: doublePrecision('min_tick').notNull(),
  margin_rate: doublePrecision('margin_rate').notNull(),
  commission: doublePrecision('commission').notNull(),
  is_active: boolean('is_active').notNull(),
  delivery_months: text('delivery_months'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const klines = pgTable('klines', {
  id: serial('id').primaryKey(),
  symbol: text('symbol').notNull(),
  period: text('period').notNull(),
  open: doublePrecision('open').notNull(),
  high: doublePrecision('high').notNull(),
  low: doublePrecision('low').notNull(),
  close: doublePrecision('close').notNull(),
  volume: doublePrecision('volume').notNull(),
  open_interest: doublePrecision('open_interest'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const signals = pgTable('signals', {
  id: serial('id').primaryKey(),
  contract: text('contract').notNull(),
  period: text('period').notNull(),
  strategy_name: text('strategy_name').notNull(),
  direction: text('direction').notNull(),
  confidence: doublePrecision('confidence').notNull(),
  price: doublePrecision('price'),
  reason: text('reason'),
  extra: json('extra'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const signal_observations = pgTable('signal_observations', {
  id: serial('id').primaryKey(),
  signal_id: text('signal_id').notNull(),
  symbol: text('symbol').notNull(),
  product: text('product').notNull(),
  direction: text('direction').notNull(),
  grade: text('grade').notNull(),
  signal_status: text('signal_status').notNull(),
  entry_price: doublePrecision('entry_price').notNull(),
  stop_loss: doublePrecision('stop_loss').notNull(),
  take_profit: doublePrecision('take_profit').notNull(),
  confidence: doublePrecision('confidence').notNull(),
  final_score: doublePrecision('final_score').notNull(),
  market_state: text('market_state').notNull(),
  payload: json('payload').notNull(),
  evaluation_status: text('evaluation_status').notNull(),
  exit_reason: text('exit_reason'),
  exit_price: doublePrecision('exit_price'),
  return_pct: doublePrecision('return_pct'),
  gross_return_pct: doublePrecision('gross_return_pct'),
  total_cost_pct: doublePrecision('total_cost_pct'),
  net_return_pct: doublePrecision('net_return_pct'),
  mfe_pct: doublePrecision('mfe_pct'),
  mae_pct: doublePrecision('mae_pct'),
  bars_held: integer('bars_held'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
  evaluated_at: timestamp('evaluated_at', { withTimezone: true }),
});

export const instrument_specifications = pgTable('instrument_specifications', {
  id: serial('id').primaryKey(),
  symbol: text('symbol').notNull(),
  asset_type: text('asset_type').notNull(),
  exchange: text('exchange').notNull(),
  contract_multiplier: doublePrecision('contract_multiplier').notNull(),
  tick_size: doublePrecision('tick_size').notNull(),
  lot_size: integer('lot_size').notNull(),
  initial_margin_rate: doublePrecision('initial_margin_rate').notNull(),
  maintenance_margin_rate: doublePrecision('maintenance_margin_rate').notNull(),
  commission_rate: doublePrecision('commission_rate').notNull(),
  stamp_duty_rate: doublePrecision('stamp_duty_rate').notNull(),
  is_active: boolean('is_active').notNull(),
  effective_from: timestamp('effective_from', { withTimezone: true }).notNull(),
  effective_to: timestamp('effective_to', { withTimezone: true }),
  metadata_json: json('metadata_json'),
});

export const paper_orders = pgTable('paper_orders', {
  id: text('id').notNull(),
  symbol: text('symbol').notNull(),
  side: text('side').notNull(),
  quantity: integer('quantity').notNull(),
  status: text('status').notNull(),
  rejection_reason: text('rejection_reason'),
  signal_time: timestamp('signal_time', { withTimezone: true }).notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const paper_fills = pgTable('paper_fills', {
  id: serial('id').primaryKey(),
  order_id: text('order_id').notNull(),
  fill_price: doublePrecision('fill_price').notNull(),
  quantity: integer('quantity').notNull(),
  commission: doublePrecision('commission').notNull(),
  slippage: doublePrecision('slippage').notNull(),
  filled_at: timestamp('filled_at', { withTimezone: true }).notNull(),
});

export const paper_runtime_controls = pgTable('paper_runtime_controls', {
  id: serial('id').primaryKey(),
  kill_switch_active: boolean('kill_switch_active').notNull(),
  kill_switch_reason: text('kill_switch_reason'),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull(),
});

export const trading_evidence_nodes = pgTable('trading_evidence_nodes', {
  evidence_id: text('evidence_id').notNull(),
  evidence_type: text('evidence_type').notNull(),
  summary: text('summary').notNull(),
  payload: json('payload').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const parameter_versions = pgTable('parameter_versions', {
  id: serial('id').primaryKey(),
  strategy_name: text('strategy_name').notNull(),
  version: integer('version').notNull(),
  params: json('params').notNull(),
  score: doublePrecision('score').notNull(),
  timestamp: doublePrecision('timestamp').notNull(),
  extra_metadata: json('extra_metadata'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const positions = pgTable('positions', {
  id: serial('id').primaryKey(),
  symbol: text('symbol').notNull(),
  direction: text('direction').notNull(),
  quantity: integer('quantity').notNull(),
  entry_price: doublePrecision('entry_price').notNull(),
  current_price: doublePrecision('current_price').notNull(),
  stop_loss: doublePrecision('stop_loss'),
  take_profit: doublePrecision('take_profit'),
  pnl: doublePrecision('pnl').notNull(),
  strategy: text('strategy').notNull(),
  status: text('status').notNull(),
  opened_at: timestamp('opened_at', { withTimezone: true }).notNull().defaultNow(),
  closed_at: timestamp('closed_at', { withTimezone: true }),
});

export const trade_records = pgTable('trade_records', {
  id: serial('id').primaryKey(),
  symbol: text('symbol').notNull(),
  direction: text('direction').notNull(),
  entry_price: doublePrecision('entry_price').notNull(),
  exit_price: doublePrecision('exit_price'),
  quantity: integer('quantity').notNull(),
  exit_time: timestamp('exit_time', { withTimezone: true }),
  pnl: doublePrecision('pnl').notNull(),
  pnl_pct: doublePrecision('pnl_pct').notNull(),
  strategy: text('strategy').notNull(),
  stop_loss: doublePrecision('stop_loss'),
  take_profit: doublePrecision('take_profit'),
  status: text('status').notNull(),
  reason: text('reason'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const backtest_results = pgTable('backtest_results', {
  id: serial('id').primaryKey(),
  name: text('name'),
  strategy: text('strategy'),
  symbol: text('symbol'),
  start_date: text('start_date'),
  end_date: text('end_date'),
  total_return: doublePrecision('total_return'),
  sharpe_ratio: doublePrecision('sharpe_ratio'),
  max_drawdown: doublePrecision('max_drawdown'),
  win_rate: doublePrecision('win_rate'),
  total_trades: integer('total_trades'),
  params: jsonb('params'),
  run_manifest: jsonb('run_manifest'),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const research_runs = pgTable('research_runs', {
  id: text('id').notNull(),
  parent_id: text('parent_id'),
  fingerprint: text('fingerprint').notNull(),
  manifest: json('manifest').notNull(),
  status: text('status').notNull(),
  metrics: json('metrics').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const performance_snapshots = pgTable('performance_snapshots', {
  id: serial('id').primaryKey(),
  snapshot_date: timestamp('snapshot_date', { withTimezone: true }).notNull(),
  strategy_name: text('strategy_name').notNull(),
  total_equity: doublePrecision('total_equity').notNull(),
  cash: doublePrecision('cash').notNull(),
  positions_value: doublePrecision('positions_value').notNull(),
  daily_pnl: doublePrecision('daily_pnl').notNull(),
  total_pnl: doublePrecision('total_pnl').notNull(),
  drawdown: doublePrecision('drawdown').notNull(),
  metrics: json('metrics'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const model_versions = pgTable('model_versions', {
  id: serial('id').primaryKey(),
  model_name: text('model_name').notNull(),
  version: text('version').notNull(),
  description: text('description'),
  metrics: json('metrics'),
  file_path: text('file_path'),
  is_active: boolean('is_active').notNull(),
  trained_at: timestamp('trained_at', { withTimezone: true }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const tournament_strategies = pgTable('tournament_strategies', {
  id: serial('id').primaryKey(),
  strategy_name: text('strategy_name').notNull(),
  tournament_round: integer('tournament_round').notNull(),
  score: doublePrecision('score').notNull(),
  sharpe: doublePrecision('sharpe').notNull(),
  win_rate: doublePrecision('win_rate').notNull(),
  total_trades: integer('total_trades').notNull(),
  total_pnl: doublePrecision('total_pnl').notNull(),
  rank: integer('rank'),
  is_active: boolean('is_active').notNull(),
  is_eliminated: boolean('is_eliminated').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const tournament_records = pgTable('tournament_records', {
  id: serial('id').primaryKey(),
  round: integer('round').notNull(),
  mode: text('mode').notNull(),
  total_strategies: integer('total_strategies').notNull(),
  eliminated_count: integer('eliminated_count').notNull(),
  summary: json('summary'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const monitor_rules = pgTable('monitor_rules', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  rule_type: text('rule_type').notNull(),
  symbol: text('symbol'),
  params: json('params').notNull(),
  level: text('level').notNull(),
  enabled: boolean('enabled').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const monitor_alerts = pgTable('monitor_alerts', {
  id: serial('id').primaryKey(),
  rule_id: integer('rule_id'),
  rule_name: text('rule_name').notNull(),
  level: text('level').notNull(),
  title: text('title').notNull(),
  message: text('message').notNull(),
  symbol: text('symbol'),
  metric_value: doublePrecision('metric_value'),
  threshold: doublePrecision('threshold'),
  acknowledged: boolean('acknowledged').notNull(),
  delivery_status: text('delivery_status').notNull(),
  delivery_attempts: integer('delivery_attempts').notNull(),
  delivery_error: text('delivery_error'),
  delivered_at: timestamp('delivered_at', { withTimezone: true }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const ops_health_snapshots = pgTable('ops_health_snapshots', {
  id: serial('id').primaryKey(),
  status: text('status').notNull(),
  metrics: json('metrics').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const llm_usage_events = pgTable('llm_usage_events', {
  id: serial('id').primaryKey(),
  provider_id: text('provider_id').notNull(),
  task: text('task').notNull(),
  prompt_tokens: integer('prompt_tokens').notNull(),
  completion_tokens: integer('completion_tokens').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const research_memories = pgTable('research_memories', {
  id: serial('id').primaryKey(),
  task_id: bigint('task_id', { mode: 'number' }),
  subject: text('subject').notNull(),
  hypothesis: text('hypothesis').notNull(),
  conclusion: text('conclusion').notNull(),
  evidence: json('evidence').notNull(),
  status: text('status').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const factor_lineage = pgTable('factor_lineage', {
  id: serial('id').primaryKey(),
  factor_name: text('factor_name').notNull(),
  version: text('version').notNull(),
  formula: text('formula').notNull(),
  asset_types: text('asset_types').notNull(),
  source_columns: text('source_columns').notNull(),
  parent_factors: text('parent_factors').notNull(),
  metrics: json('metrics').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const strategy_lifecycle = pgTable('strategy_lifecycle', {
  id: serial('id').primaryKey(),
  strategy_name: text('strategy_name').notNull(),
  stage: text('stage').notNull(),
  version: text('version').notNull(),
  evidence: json('evidence').notNull(),
  last_reason: text('last_reason'),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull(),
});

export const agent_tasks = pgTable('agent_tasks', {
  id: serial('id').primaryKey(),
  goal: text('goal').notNull(),
  asset_type: text('asset_type').notNull(),
  symbols: text('symbols').notNull(),
  status: text('status').notNull(),
  trigger: text('trigger').notNull(),
  created_by: text('created_by').notNull(),
  idempotency_key: text('idempotency_key'),
  error_code: text('error_code'),
  error_message: text('error_message'),
  planned_cost_units: integer('planned_cost_units').notNull(),
  reserved_cost_units: integer('reserved_cost_units').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull(),
  started_at: timestamp('started_at', { withTimezone: true }),
  finished_at: timestamp('finished_at', { withTimezone: true }),
  lease_owner: text('lease_owner'),
  last_heartbeat_at: timestamp('last_heartbeat_at', { withTimezone: true }),
  lease_expires_at: timestamp('lease_expires_at', { withTimezone: true }),
  recovery_attempts: integer('recovery_attempts').notNull(),
});

export const agent_runtime_controls = pgTable('agent_runtime_controls', {
  id: serial('id').primaryKey(),
  max_concurrent: integer('max_concurrent').notNull(),
  running_count: integer('running_count').notNull(),
  daily_budget_units: integer('daily_budget_units').notNull(),
  consumed_budget_units: integer('consumed_budget_units').notNull(),
  circuit_open_until: timestamp('circuit_open_until', { withTimezone: true }),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull(),
});

export const agent_steps = pgTable('agent_steps', {
  id: serial('id').primaryKey(),
  task_id: bigint('task_id', { mode: 'number' }).notNull(),
  step_key: text('step_key').notNull(),
  step_type: text('step_type').notNull(),
  depends_on: text('depends_on').notNull(),
  status: text('status').notNull(),
  tool_name: text('tool_name'),
  input_payload: json('input_payload').notNull(),
  output_payload: json('output_payload'),
  attempt_count: integer('attempt_count').notNull(),
  max_retries: integer('max_retries').notNull(),
  timeout_seconds: integer('timeout_seconds').notNull(),
  error_code: text('error_code'),
  error_message: text('error_message'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
  started_at: timestamp('started_at', { withTimezone: true }),
  finished_at: timestamp('finished_at', { withTimezone: true }),
});

export const agent_tool_calls = pgTable('agent_tool_calls', {
  id: serial('id').primaryKey(),
  task_id: bigint('task_id', { mode: 'number' }).notNull(),
  step_id: bigint('step_id', { mode: 'number' }),
  tool_name: text('tool_name').notNull(),
  tool_version: text('tool_version').notNull(),
  idempotency_key: text('idempotency_key').notNull(),
  input_payload: json('input_payload').notNull(),
  result_payload: json('result_payload'),
  success: boolean('success').notNull(),
  error_code: text('error_code'),
  error_message: text('error_message'),
  duration_ms: integer('duration_ms'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const agent_artifacts = pgTable('agent_artifacts', {
  id: serial('id').primaryKey(),
  task_id: bigint('task_id', { mode: 'number' }).notNull(),
  step_id: bigint('step_id', { mode: 'number' }),
  artifact_type: text('artifact_type').notNull(),
  name: text('name').notNull(),
  payload: json('payload').notNull(),
  version: text('version').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const agent_evidence = pgTable('agent_evidence', {
  id: serial('id').primaryKey(),
  task_id: bigint('task_id', { mode: 'number' }).notNull(),
  step_id: bigint('step_id', { mode: 'number' }),
  artifact_id: bigint('artifact_id', { mode: 'number' }),
  evidence_type: text('evidence_type').notNull(),
  source: text('source').notNull(),
  data_start: timestamp('data_start', { withTimezone: true }),
  data_end: timestamp('data_end', { withTimezone: true }),
  quality: json('quality').notNull(),
  payload: json('payload').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const agent_approvals = pgTable('agent_approvals', {
  id: serial('id').primaryKey(),
  task_id: bigint('task_id', { mode: 'number' }).notNull(),
  step_id: bigint('step_id', { mode: 'number' }),
  action: text('action').notNull(),
  reason: text('reason').notNull(),
  status: text('status').notNull(),
  requested_by: text('requested_by').notNull(),
  decided_by: text('decided_by'),
  decision_note: text('decision_note'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
  expires_at: timestamp('expires_at', { withTimezone: true }),
  decided_at: timestamp('decided_at', { withTimezone: true }),
});

export const agent_events = pgTable('agent_events', {
  id: serial('id').primaryKey(),
  task_id: bigint('task_id', { mode: 'number' }).notNull(),
  step_id: bigint('step_id', { mode: 'number' }),
  event_type: text('event_type').notNull(),
  payload: json('payload').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull(),
});

// === 7大核心品种与专业量化规范 14 张核心表 ===
export const market_bars = pgTable('market_bars', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }).notNull(),
  symbol: varchar('symbol', { length: 30 }),
  frequency: varchar('frequency', { length: 10 }).notNull(), // 'D1', 'H1', 'M30'
  trading_date: date('trading_date').notNull(),
  bar_start: timestamp('bar_start', { withTimezone: true }).notNull(),
  bar_end: timestamp('bar_end', { withTimezone: true }).notNull(),
  session: varchar('session', { length: 30 }).notNull(),
  open: doublePrecision('open').notNull(),
  high: doublePrecision('high').notNull(),
  low: doublePrecision('low').notNull(),
  close: doublePrecision('close').notNull(),
  volume: bigint('volume', { mode: 'number' }).notNull(),
  turnover: doublePrecision('turnover'),
  open_interest: bigint('open_interest', { mode: 'number' }).notNull(),
  settlement: doublePrecision('settlement'),
  pre_settlement: doublePrecision('pre_settlement'),
  pre_close: doublePrecision('pre_close'),
  upper_limit: doublePrecision('upper_limit'),
  lower_limit: doublePrecision('lower_limit'),
  source_count: integer('source_count').default(60),
  expected_count: integer('expected_count').default(60),
  missing_count: integer('missing_count').default(0),
  is_finalized: boolean('is_finalized').notNull().default(true),
  quality_status: varchar('quality_status', { length: 20 }).notNull().default('complete'),
  roll_transition: boolean('roll_transition').notNull().default(false),
  source_id: varchar('source_id', { length: 100 }).notNull().default('ctp-sync'),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  acquired_at: timestamp('acquired_at', { withTimezone: true }).notNull().defaultNow(),
  schema_version: varchar('schema_version', { length: 30 }).notNull().default('market-bar.v1'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const realtime_stream_buffer = pgTable('realtime_stream_buffer', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }).notNull(),
  trading_date: date('trading_date').notNull(),
  action_date: date('action_date').notNull(),
  update_time: varchar('update_time', { length: 20 }).notNull(),
  update_millisec: integer('update_millisec').default(0),
  received_at: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
  last_price: doublePrecision('last_price').notNull(),
  volume: bigint('volume', { mode: 'number' }).notNull(),
  turnover: doublePrecision('turnover'),
  open_interest: bigint('open_interest', { mode: 'number' }).notNull(),
  bid_price_1: doublePrecision('bid_price_1'),
  bid_volume_1: integer('bid_volume_1'),
  ask_price_1: doublePrecision('ask_price_1'),
  ask_volume_1: integer('ask_volume_1'),
  upper_limit: doublePrecision('upper_limit').notNull(),
  lower_limit: doublePrecision('lower_limit').notNull(),
  sequence_id: bigint('sequence_id', { mode: 'number' }).notNull(),
  source_session_id: varchar('source_session_id', { length: 64 }).notNull(),
  is_duplicate: boolean('is_duplicate').notNull().default(false),
  is_late: boolean('is_late').notNull().default(false),
  latency_ms: integer('latency_ms').default(0),
  raw_payload_sha256: varchar('raw_payload_sha256', { length: 64 }).default(''),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const trading_sessions = pgTable('trading_sessions', {
  id: serial('id').primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  effective_from: date('effective_from').notNull(),
  effective_to: date('effective_to'),
  session_name: varchar('session_name', { length: 50 }).notNull(),
  session_start: varchar('session_start', { length: 10 }).notNull(),
  session_end: varchar('session_end', { length: 10 }).notNull(),
  crosses_midnight: boolean('crosses_midnight').notNull().default(false),
  trading_date_rule: varchar('trading_date_rule', { length: 50 }).notNull().default('next_trading_day_for_night'),
  auction_start: varchar('auction_start', { length: 10 }),
  auction_end: varchar('auction_end', { length: 10 }),
  is_trading_day: boolean('is_trading_day').notNull().default(true),
  previous_trading_day: date('previous_trading_day'),
  next_trading_day: date('next_trading_day'),
  holiday_name: varchar('holiday_name', { length: 50 }),
  night_session_enabled: boolean('night_session_enabled').notNull().default(true),
  source_url: text('source_url').notNull().default(''),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const contract_specs = pgTable('contract_specs', {
  id: serial('id').primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }),
  contract_name: varchar('contract_name', { length: 100 }).notNull(),
  listed_date: date('listed_date').notNull(),
  last_trading_date: date('last_trading_date').notNull(),
  delivery_month: varchar('delivery_month', { length: 10 }).notNull(),
  contract_multiplier: doublePrecision('contract_multiplier').notNull(),
  price_tick: doublePrecision('price_tick').notNull(),
  quotation_unit: varchar('quotation_unit', { length: 30 }).notNull(),
  minimum_order_volume: integer('minimum_order_volume').notNull().default(1),
  maximum_order_volume: integer('maximum_order_volume').default(500),
  position_limit: integer('position_limit'),
  delivery_unit: doublePrecision('delivery_unit'),
  limit_ratio: doublePrecision('limit_ratio').notNull(),
  effective_from: timestamp('effective_from', { withTimezone: true }).notNull(),
  effective_to: timestamp('effective_to', { withTimezone: true }),
  source_class: varchar('source_class', { length: 30 }).notNull().default('official'),
  source_url: text('source_url').notNull().default(''),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  historical_authority: boolean('historical_authority').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const fee_and_margins = pgTable('fee_and_margins', {
  id: serial('id').primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }),
  broker: varchar('broker', { length: 50 }),
  effective_from: timestamp('effective_from', { withTimezone: true }).notNull(),
  effective_to: timestamp('effective_to', { withTimezone: true }),
  long_margin_ratio: doublePrecision('long_margin_ratio').notNull(),
  short_margin_ratio: doublePrecision('short_margin_ratio').notNull(),
  exchange_margin_ratio: doublePrecision('exchange_margin_ratio'),
  broker_margin_addon: doublePrecision('broker_margin_addon').default(0),
  open_fee_per_lot: doublePrecision('open_fee_per_lot').notNull().default(0),
  open_fee_ratio: doublePrecision('open_fee_ratio').notNull().default(0),
  close_fee_per_lot: doublePrecision('close_fee_per_lot').notNull().default(0),
  close_fee_ratio: doublePrecision('close_fee_ratio').notNull().default(0),
  close_today_fee_per_lot: doublePrecision('close_today_fee_per_lot').notNull().default(0),
  close_today_fee_ratio: doublePrecision('close_today_fee_ratio').notNull().default(0),
  estimated_slippage_ticks: doublePrecision('estimated_slippage_ticks').default(1.0),
  source_url: text('source_url').notNull().default(''),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  verified: boolean('verified').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const dominant_contracts_history = pgTable('dominant_contracts_history', {
  id: serial('id').primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  trading_date: date('trading_date').notNull(),
  active_contract: varchar('active_contract', { length: 30 }).notNull(),
  previous_contract: varchar('previous_contract', { length: 30 }),
  next_contract: varchar('next_contract', { length: 30 }),
  switch_occurred: boolean('switch_occurred').notNull().default(false),
  switch_reason: varchar('switch_reason', { length: 50 }).notNull().default('open_interest_max'),
  old_volume: bigint('old_volume', { mode: 'number' }),
  new_volume: bigint('new_volume', { mode: 'number' }),
  old_open_interest: bigint('old_open_interest', { mode: 'number' }),
  new_open_interest: bigint('new_open_interest', { mode: 'number' }),
  confirmation_days: integer('confirmation_days').notNull().default(3),
  roll_price_gap: doublePrecision('roll_price_gap').notNull().default(0),
  return_excluded: boolean('return_excluded').notNull().default(true),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  rule_version: varchar('rule_version', { length: 30 }).notNull().default('oi_dominance_v1'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const member_positions = pgTable('member_positions', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }).notNull(),
  trading_date: date('trading_date').notNull(),
  member: varchar('member', { length: 100 }).notNull(),
  rank: integer('rank').notNull(),
  volume: bigint('volume', { mode: 'number' }).notNull().default(0),
  long_position: bigint('long_position', { mode: 'number' }).notNull().default(0),
  long_change: bigint('long_change', { mode: 'number' }).notNull().default(0),
  short_position: bigint('short_position', { mode: 'number' }).notNull().default(0),
  short_change: bigint('short_change', { mode: 'number' }).notNull().default(0),
  publication_time: timestamp('publication_time', { withTimezone: true }).notNull(),
  available_at: timestamp('available_at', { withTimezone: true }).notNull(),
  source_url: text('source_url').notNull().default(''),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const warehouse_receipts = pgTable('warehouse_receipts', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  region: varchar('region', { length: 50 }),
  warehouse: varchar('warehouse', { length: 100 }),
  observation_date: date('observation_date').notNull(),
  publication_time: timestamp('publication_time', { withTimezone: true }).notNull(),
  available_at: timestamp('available_at', { withTimezone: true }).notNull(),
  warehouse_receipt: doublePrecision('warehouse_receipt').notNull(),
  warehouse_receipt_change: doublePrecision('warehouse_receipt_change').notNull(),
  inventory: doublePrecision('inventory'),
  inventory_change: doublePrecision('inventory_change'),
  unit: varchar('unit', { length: 20 }).notNull().default('吨'),
  revision_id: varchar('revision_id', { length: 30 }).notNull().default('rev-01'),
  source_url: text('source_url').notNull().default(''),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const industry_fundamentals = pgTable('industry_fundamentals', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  product: varchar('product', { length: 20 }).notNull(),
  indicator_code: varchar('indicator_code', { length: 60 }).notNull(),
  indicator_name: varchar('indicator_name', { length: 100 }).notNull(),
  observation_date: date('observation_date').notNull(),
  publication_time: timestamp('publication_time', { withTimezone: true }).notNull(),
  available_at: timestamp('available_at', { withTimezone: true }).notNull(),
  value: doublePrecision('value').notNull(),
  unit: varchar('unit', { length: 30 }).notNull(),
  region: varchar('region', { length: 50 }),
  frequency: varchar('frequency', { length: 20 }).notNull().default('daily'),
  revision_id: varchar('revision_id', { length: 30 }).notNull().default('rev-01'),
  source_name: varchar('source_name', { length: 100 }).notNull(),
  source_url: text('source_url').notNull().default(''),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  official: boolean('official').notNull().default(true),
  effective_dated: boolean('effective_dated').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const macro_indicators = pgTable('macro_indicators', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  indicator_code: varchar('indicator_code', { length: 50 }).notNull(),
  indicator_name: varchar('indicator_name', { length: 100 }).notNull(),
  country: varchar('country', { length: 10 }).notNull().default('CN'),
  period: varchar('period', { length: 20 }).notNull(),
  value: doublePrecision('value').notNull(),
  previous_value: doublePrecision('previous_value'),
  forecast_value: doublePrecision('forecast_value'),
  unit: varchar('unit', { length: 30 }).notNull(),
  release_time: timestamp('release_time', { withTimezone: true }).notNull(),
  available_at: timestamp('available_at', { withTimezone: true }).notNull(),
  revision_time: timestamp('revision_time', { withTimezone: true }),
  revision_id: varchar('revision_id', { length: 30 }).notNull().default('v1'),
  source_agency: varchar('source_agency', { length: 100 }).notNull(),
  source_url: text('source_url').notNull().default(''),
  source_sha256: varchar('source_sha256', { length: 64 }).notNull().default(''),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const factor_values = pgTable('factor_values', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  factor_id: varchar('factor_id', { length: 100 }).notNull(),
  factor_name: varchar('factor_name', { length: 100 }).notNull(),
  factor_family: varchar('factor_family', { length: 50 }).notNull(),
  factor_version: varchar('factor_version', { length: 30 }).notNull(),
  logic_sha256: varchar('logic_sha256', { length: 64 }).notNull(),
  parameter_sha256: varchar('parameter_sha256', { length: 64 }).notNull(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }).notNull(),
  frequency: varchar('frequency', { length: 10 }).notNull(),
  as_of: timestamp('as_of', { withTimezone: true }).notNull(),
  available_data_cutoff: timestamp('available_data_cutoff', { withTimezone: true }).notNull(),
  value: doublePrecision('value').notNull(),
  normalized_value: doublePrecision('normalized_value'),
  direction: varchar('direction', { length: 20 }).notNull(),
  confidence: doublePrecision('confidence').default(0.8),
  quality_status: varchar('quality_status', { length: 20 }).notNull().default('complete'),
  input_hashes: json('input_hashes').notNull(),
  research_only: boolean('research_only').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const strategy_signals = pgTable('strategy_signals', {
  id: text('id').primaryKey(),
  candidate_id: varchar('candidate_id', { length: 100 }).notNull(),
  strategy_family: varchar('strategy_family', { length: 50 }).notNull(),
  strategy_version: varchar('strategy_version', { length: 30 }).notNull(),
  logic_sha256: varchar('logic_sha256', { length: 64 }).notNull(),
  parameter_sha256: varchar('parameter_sha256', { length: 64 }).notNull(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }).notNull(),
  signal_frequency: varchar('signal_frequency', { length: 10 }).notNull().default('H1'),
  confirmation_frequency: varchar('confirmation_frequency', { length: 10 }).default('M30'),
  generated_at: timestamp('generated_at', { withTimezone: true }).notNull(),
  data_cutoff: timestamp('data_cutoff', { withTimezone: true }).notNull(),
  market_regime: varchar('market_regime', { length: 50 }).notNull(),
  target_position: integer('target_position').notNull(),
  action: varchar('action', { length: 30 }).notNull(),
  reason_code: varchar('reason_code', { length: 50 }).notNull(),
  reason_text: text('reason_text').notNull(),
  entry_reference_price: doublePrecision('entry_reference_price'),
  invalidation_price: doublePrecision('invalidation_price').notNull(),
  stop_price: doublePrecision('stop_price').notNull(),
  take_profit_price: doublePrecision('take_profit_price'),
  maximum_holding_bars: integer('maximum_holding_bars'),
  risk_per_lot: doublePrecision('risk_per_lot').notNull(),
  margin_per_lot: doublePrecision('margin_per_lot').notNull(),
  estimated_round_trip_cost: doublePrecision('estimated_round_trip_cost').notNull(),
  capital_allowed: boolean('capital_allowed').notNull().default(true),
  quality_status: varchar('quality_status', { length: 20 }).notNull().default('complete'),
  human_approval_required: boolean('human_approval_required').notNull().default(true),
  research_only: boolean('research_only').notNull().default(true),
  execution_enabled: boolean('execution_enabled').notNull().default(false),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const manual_positions = pgTable('manual_positions', {
  position_id: varchar('position_id', { length: 64 }).primaryKey(),
  account_alias: varchar('account_alias', { length: 50 }).notNull(),
  exchange: varchar('exchange', { length: 20 }).notNull(),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }).notNull(),
  direction: varchar('direction', { length: 10 }).notNull(),
  lots: integer('lots').notNull(),
  entry_time: timestamp('entry_time', { withTimezone: true }).notNull(),
  entry_price: doublePrecision('entry_price').notNull(),
  entry_signal_id: varchar('entry_signal_id', { length: 64 }),
  stop_price: doublePrecision('stop_price').notNull(),
  take_profit_price: doublePrecision('take_profit_price'),
  maximum_holding_until: timestamp('maximum_holding_until', { withTimezone: true }).notNull(),
  current_status: varchar('current_status', { length: 20 }).notNull().default('open'),
  exit_time: timestamp('exit_time', { withTimezone: true }),
  exit_price: doublePrecision('exit_price'),
  exit_reason: text('exit_reason'),
  realized_pnl: doublePrecision('realized_pnl'),
  fees_paid: doublePrecision('fees_paid'),
  manually_confirmed: boolean('manually_confirmed').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const exit_alerts = pgTable('exit_alerts', {
  alert_id: text('alert_id').primaryKey(),
  fingerprint: varchar('fingerprint', { length: 100 }).notNull().unique(),
  position_id: varchar('position_id', { length: 64 }).notNull(),
  signal_id: varchar('signal_id', { length: 64 }),
  product: varchar('product', { length: 20 }).notNull(),
  contract: varchar('contract', { length: 30 }).notNull(),
  alert_type: varchar('alert_type', { length: 30 }).notNull(),
  severity: varchar('severity', { length: 20 }).notNull(),
  triggered_at: timestamp('triggered_at', { withTimezone: true }).notNull().defaultNow(),
  bar_frequency: varchar('bar_frequency', { length: 10 }).notNull(),
  bar_end: timestamp('bar_end', { withTimezone: true }).notNull(),
  market_price: doublePrecision('market_price').notNull(),
  trigger_price: doublePrecision('trigger_price'),
  reason_code: varchar('reason_code', { length: 50 }).notNull(),
  message: text('message').notNull(),
  recommended_action: varchar('recommended_action', { length: 30 }).notNull(),
  data_quality_status: varchar('data_quality_status', { length: 20 }).notNull().default('complete'),
  acknowledged_at: timestamp('acknowledged_at', { withTimezone: true }),
  delivery_target: varchar('delivery_target', { length: 50 }).notNull().default('internal_dashboard'),
  delivery_status: varchar('delivery_status', { length: 20 }).notNull().default('delivered'),
  attempt_count: integer('attempt_count').notNull().default(1),
  last_error: text('last_error'),
  execution_enabled: boolean('execution_enabled').notNull().default(false),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const data_audit_logs = pgTable('data_audit_logs', {
  bundle_id: varchar('bundle_id', { length: 64 }).primaryKey(),
  dataset_type: varchar('dataset_type', { length: 30 }).notNull(),
  source_name: varchar('source_name', { length: 100 }).notNull(),
  source_class: varchar('source_class', { length: 30 }).notNull(),
  source_url: text('source_url').notNull().default(''),
  acquired_at: timestamp('acquired_at', { withTimezone: true }).notNull().defaultNow(),
  source_document_sha256: varchar('source_document_sha256', { length: 64 }).default(''),
  source_payload_sha256: varchar('source_payload_sha256', { length: 64 }).default(''),
  row_count: integer('row_count').notNull(),
  first_timestamp: timestamp('first_timestamp', { withTimezone: true }),
  last_timestamp: timestamp('last_timestamp', { withTimezone: true }),
  duplicate_count: integer('duplicate_count').notNull().default(0),
  missing_count: integer('missing_count').notNull().default(0),
  rejected_count: integer('rejected_count').notNull().default(0),
  revision_count: integer('revision_count').notNull().default(0),
  coverage_status: varchar('coverage_status', { length: 20 }).notNull().default('complete'),
  historical_authority: boolean('historical_authority').notNull().default(true),
  effective_dated: boolean('effective_dated').notNull().default(true),
  validation_version: varchar('validation_version', { length: 30 }).notNull().default('audit_v1'),
  validation_status: varchar('validation_status', { length: 20 }).notNull().default('accepted'),
  failure_reasons: json('failure_reasons').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
